# Generated by Django 3.2.12 on 2023-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='additionalOwner',
            field=models.BooleanField(default=False),
        ),
    ]
