# Generated by Django 3.2.12 on 2022-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='additionalInsureds',
            field=models.ManyToManyField(related_name='namedinsured', to='Insurance.NamedInsured'),
        ),
    ]
