# Generated by Django 2.2 on 2022-01-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_carsdb_namedinsured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsdb',
            old_name='carType',
            new_name='bodyStyle',
        ),
        migrations.AddField(
            model_name='carsdb',
            name='pickTrim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
