# Generated by Django 2.2 on 2022-01-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_auto_20220111_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyStyle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurance.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='PickTrimEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickTrim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YearEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurance.Model')),
            ],
        ),
        migrations.DeleteModel(
            name='CarsDB',
        ),
        migrations.AddField(
            model_name='picktrimentry',
            name='yearEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.YearEntry'),
        ),
        migrations.AddField(
            model_name='bodystyleentry',
            name='yearEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.YearEntry'),
        ),
    ]
