# Generated by Django 3.2.12 on 2023-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_prospect_lapses'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='centralHeat',
            field=models.BooleanField(default=False),
        ),
    ]
