# Generated by Django 2.2 on 2022-01-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0004_auto_20220113_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='abvr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
