# Generated by Django 2.2 on 2022-01-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0005_brand_abvr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='abvr',
        ),
        migrations.AddField(
            model_name='brand',
            name='short',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
