# Generated by Django 2.2 on 2022-01-15 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0006_auto_20220113_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyDamageCoverage', models.IntegerField(blank=True, default=10000, null=True)),
                ('biCoverage', models.IntegerField(blank=True, null=True)),
                ('uninsuredMotorist', models.CharField(blank=True, max_length=50, null=True)),
                ('pipDeductible', models.IntegerField(default=1000)),
                ('rentalDeductible', models.IntegerField(blank=True, null=True)),
                ('towingDeductible', models.IntegerField(blank=True, null=True)),
                ('homeOwner', models.BooleanField(blank=True, default=False, null=True)),
                ('millitary', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialAutoQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoveredAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collisionDeductible', models.IntegerField(blank=True, null=True)),
                ('autoquotelements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.AutoQuoteElements')),
            ],
        ),
        migrations.CreateModel(
            name='HealthQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomeQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('propertyType', models.CharField(blank=True, max_length=50, null=True)),
                ('propertyRoof', models.CharField(blank=True, max_length=50, null=True)),
                ('propertyRoofType', models.CharField(blank=True, max_length=50, null=True)),
                ('propertyRoofMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('propertyRoofColor', models.CharField(blank=True, max_length=50, null=True)),
                ('coverageA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverageB', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverageC', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverageD', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverageE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverageF', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sinkholeCoverage', models.BooleanField(blank=True, default=False, null=True)),
                ('hurricaineDeductible', models.CharField(blank=True, max_length=50, null=True)),
                ('rentalDeductible', models.IntegerField(blank=True, null=True)),
                ('towingDeductible', models.IntegerField(blank=True, null=True)),
                ('millitary', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('short', models.CharField(blank=True, max_length=15, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UWFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='collisionDeductible',
        ),
        migrations.RemoveField(
            model_name='car',
            name='comprehensiveDeductible',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pipDeductible',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rentalDeductible',
        ),
        migrations.RemoveField(
            model_name='car',
            name='towingDeductible',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='biCoverage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='driversLicense',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='homeOwner',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='homeOwnership',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='medicalCoverage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='propertyDamageCoverage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uninsuredMotorist',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='picktrimentry',
            name='yearEntry',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='company',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='downpayment',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='monthlypayment',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='totalpayment',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profilePicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PersonalImage'),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='driversLicense',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='maritalStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='ssn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='picktrimentry',
            name='bodyStyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.BodyStyleEntry'),
        ),
        migrations.AddField(
            model_name='quote',
            name='businessType',
            field=models.CharField(blank=True, choices=[('PA', 'Personal Auto'), ('CA', 'Commercial Auto'), ('HO', 'HomeOwners')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='downPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='monthlyPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='totalPremium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='namedinsured',
            name='relationship',
            field=models.CharField(blank=True, choices=[('MAIN INSURED', 'Main Insured'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalimage',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalimage',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AdditionalDriver',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='uwfile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='additionalInsureds',
            field=models.ManyToManyField(blank=True, null=True, related_name='HOadditionalInsureds', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HOmainInsured', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='propertyAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Address'),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Car'),
        ),
        migrations.AddField(
            model_name='autoquoteelements',
            name='additionalInsureds',
            field=models.ManyToManyField(blank=True, null=True, related_name='additionalInsureds', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='autoquoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainInsured', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='autoquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Address'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Insurer'),
        ),
    ]
