# Generated by Django 2.2 on 2022-01-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0007_auto_20220115_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='rentalDeductible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autoquoteelements',
            name='additionalInsureds',
            field=models.ManyToManyField(blank=True, related_name='additionalInsureds', to='Insurance.NamedInsured'),
        ),
        migrations.AlterField(
            model_name='homequoteelements',
            name='additionalInsureds',
            field=models.ManyToManyField(blank=True, related_name='HOadditionalInsureds', to='Insurance.NamedInsured'),
        ),
    ]
