# Generated by Django 2.2 on 2022-01-16 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0008_auto_20220115_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyName', models.CharField(blank=True, max_length=50, null=True)),
                ('agencyEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('agencyPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('agencyWebsite', models.CharField(blank=True, max_length=50, null=True)),
                ('agencyLogo', models.CharField(blank=True, max_length=50, null=True)),
                ('agencyAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Address')),
                ('agencyDocuments', models.ManyToManyField(blank=True, related_name='agencyDocuments', to='Insurance.UWFile')),
                ('agencyOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agencyUWFiles', models.ManyToManyField(blank=True, related_name='agencyUWFiles', to='Insurance.UWFile')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producerCode', models.CharField(blank=True, max_length=50, null=True)),
                ('webUsername', models.CharField(blank=True, max_length=50, null=True)),
                ('webPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('webURL', models.CharField(blank=True, max_length=50, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Agency')),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Insurer')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=50)),
                ('routingNumber', models.CharField(max_length=50)),
                ('accountNumber', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=50)),
                ('accountHolderName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=16)),
                ('cardType', models.CharField(max_length=50)),
                ('expirationDate', models.CharField(max_length=50)),
                ('cardHolderName', models.CharField(max_length=50)),
                ('cardSecurityCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=50, null=True)),
                ('companyFein', models.CharField(blank=True, max_length=50, null=True)),
                ('companyType', models.CharField(blank=True, max_length=50, null=True)),
                ('totalPayroll', models.IntegerField(blank=True, null=True)),
                ('numberOfEmployees', models.IntegerField(blank=True, null=True)),
                ('companyActivityDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('companyStartDate', models.DateField(blank=True, null=True)),
                ('yearsOfExperience', models.IntegerField(blank=True, null=True)),
                ('companyPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('companyFax', models.CharField(blank=True, max_length=50, null=True)),
                ('companyEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('companyWebsite', models.CharField(blank=True, max_length=50, null=True)),
                ('companyAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Address')),
                ('companyOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoAddress', models.CharField(max_length=50)),
                ('cryptoType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsementDate', models.DateField()),
                ('endorsementType', models.CharField(max_length=50)),
                ('endorsementStatus', models.CharField(max_length=50)),
                ('endorsementDocuments', models.ManyToManyField(blank=True, related_name='endorsementDocuments', to='Insurance.UWFile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downPayment', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paymentDate', models.DateField(blank=True, null=True)),
                ('paymentType', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paymentRef', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentRef2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('paymentMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAutoQuoteElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyDamageCoverage', models.IntegerField(blank=True, default=10000, null=True)),
                ('biCoverage', models.IntegerField(blank=True, null=True)),
                ('uninsuredMotorist', models.CharField(blank=True, max_length=50, null=True)),
                ('pipCoverage', models.IntegerField(default=10000)),
                ('pipDeductible', models.IntegerField(default=1000)),
                ('rentalDeductible', models.IntegerField(blank=True, null=True)),
                ('towingDeductible', models.IntegerField(blank=True, null=True)),
                ('homeOwner', models.BooleanField(blank=True, default=False, null=True)),
                ('millitary', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commisionAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commisionPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commisionPaid', models.BooleanField(default=False)),
                ('bindDate', models.DateField()),
                ('effectiveDate', models.DateField()),
                ('expirationDate', models.DateField()),
                ('policyLength', models.IntegerField(blank=True, null=True)),
                ('policyNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('policyType', models.CharField(blank=True, max_length=50, null=True)),
                ('policyStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('policyPremium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Agency')),
                ('downPayment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policyDownPayment', to='Insurance.Payment')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policyDocuments', models.ManyToManyField(blank=True, related_name='policyDocuments', to='Insurance.UWFile')),
                ('policyHolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policyHolder', to=settings.AUTH_USER_MODEL)),
                ('policyPayments', models.ManyToManyField(blank=True, related_name='policyPayments', to='Insurance.Payment')),
                ('policyUWFiles', models.ManyToManyField(blank=True, related_name='policyUWFiles', to='Insurance.UWFile')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='PriorInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('effectiveDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurance.Insurer')),
                ('priorDocument', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.UWFile')),
            ],
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='rentalDeductible',
            new_name='allPerilsDeuctible',
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='coverageA',
            new_name='dwellingCoverage',
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='coverageC',
            new_name='liabiltyLimit',
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='coverageD',
            new_name='lossOfUseCoverage',
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='towingDeductible',
            new_name='numberOfDogs',
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='coverageE',
            new_name='personalPropertyCoverage',
        ),
        migrations.RenameField(
            model_name='homequoteelements',
            old_name='coverageF',
            new_name='purchasePrice',
        ),
        migrations.AddField(
            model_name='businessquoteelements',
            name='liabiltyLimit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessquoteelements',
            name='planType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='additionalInsureds',
            field=models.ManyToManyField(blank=True, to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='biCoverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='homeOwner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainCAInsured', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='millitary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='ownedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='pipDeductible',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='propertyDamageCoverage',
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='rentalDeductible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='towingDeductible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='uninsuredMotorist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthquoteelements',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthquoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='healthquoteelements',
            name='planType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='WMInspectionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='buildingCodeGrade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='deadboltLock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='electricalWiringUpdateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='electricalWiringUpdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='fbcWindSpeed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='fbcWindSpeedDesign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='fireAlarm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='fireAlarmType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='fireExtinguisher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='heatingSystemUpdateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='heatingSystemUpdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='heatingType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='medicalPayments',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='numberOfFamilies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='numberOfTenants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='openingProtection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='overhang',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='plumbingSystemUpdateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='plumbingSystemUpdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='protectionClass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='replacementCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='roofCover',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='roofDeckAttachment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='roofShape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='roofUpdateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='roofUpdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='roofWallConnection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='secondaryWindResistance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='skyLight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='smokeDetector',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='sprinklerSystem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='terrainType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lifequoteelements',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifequoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='lifequoteelements',
            name='planType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lifequoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='namedinsured',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coveredauto',
            name='autoquotelements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PersonalAutoQuoteElements'),
        ),
        migrations.DeleteModel(
            name='AutoQuoteElements',
        ),
        migrations.AddField(
            model_name='personalautoquoteelements',
            name='additionalInsureds',
            field=models.ManyToManyField(blank=True, related_name='additionalPAInsureds', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='personalautoquoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainPAInsured', to='Insurance.NamedInsured'),
        ),
        migrations.AddField(
            model_name='personalautoquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentMethod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorsementPayment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsementDownPayment', to='Insurance.Payment'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorsementPayments',
            field=models.ManyToManyField(blank=True, related_name='endorsementPayments', to='Insurance.Payment'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorsementUWFiles',
            field=models.ManyToManyField(blank=True, related_name='endorsementUWFiles', to='Insurance.UWFile'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Policy'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='paymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='card',
            name='paymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='paymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='businessquoteelements',
            name='mainInsured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Company'),
        ),
        migrations.AddField(
            model_name='quote',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Agency'),
        ),
    ]
