# Generated by Django 2.2 on 2022-01-16 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0009_auto_20220116_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='paymentType',
            new_name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agencyEmail',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agencyName',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agencyPhone',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='card',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paypal',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='insured',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crypto',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bankAccount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.BankAccount'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Card'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='crypto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Crypto'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paypal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.PayPal'),
        ),
        migrations.AddField(
            model_name='paypal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priorinsurance',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AlterField(
            model_name='priorinsurance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priorinsurance',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Insurer'),
        ),
    ]
