# Generated by Django 2.2 on 2022-01-18 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0011_auto_20220116_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='homequoteelements',
            name='dateOccupied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnoccupiedMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('short', models.CharField(blank=True, max_length=50, null=True)),
                ('homeOwnerQuoteElement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.HomeQuoteElements')),
            ],
        ),
    ]
