# Generated by Django 2.2 on 2022-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0013_auto_20220118_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unoccupiedmonth',
            name='unoccupiedMonths',
            field=models.ManyToManyField(blank=True, to='Insurance.CalendarMonth'),
        ),
    ]
