# Generated by Django 2.2 on 2022-01-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0014_auto_20220118_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agencyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
