# Generated by Django 3.2.12 on 2023-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0015_auto_20230205_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
