# Generated by Django 3.2.12 on 2023-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0016_alter_prospect_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='additionalOwner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='centralHeat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='claims',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='damage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='inspections',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='lapses',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='married',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mortgage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='primary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='prior',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
