# Generated by Django 2.2 on 2022-01-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0016_auto_20220118_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unoccupiedmonth',
            name='homeOwnerQuoteElement',
        ),
        migrations.RemoveField(
            model_name='unoccupiedmonth',
            name='unoccupiedMonths',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agencyName',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.RemoveField(
            model_name='homequoteelements',
            name='dateOccupied',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='BusinessQuoteElements',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='CAQuoteElements',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='HOQuoteElements',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='HealthQuoteElements',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='LifeQuoteElements',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='PAQuoteElements',
        ),
        migrations.AddField(
            model_name='businessquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='commercialautoquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='healthquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='homequoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='lifequoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.AddField(
            model_name='personalautoquoteelements',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.Quote'),
        ),
        migrations.DeleteModel(
            name='CalendarMonth',
        ),
        migrations.DeleteModel(
            name='UnoccupiedMonth',
        ),
    ]
