# Generated by Django 3.2.12 on 2022-05-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0017_auto_20220128_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
