# Generated by Django 3.2.12 on 2023-02-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0017_auto_20230205_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='mortgagee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
