# Generated by Django 3.2.12 on 2023-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0018_alter_prospect_mortgagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='coverageA',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
