# Generated by Django 3.2.12 on 2022-05-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0018_alter_address_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=25, null=True)),
                ('model', models.CharField(blank=True, max_length=60, null=True)),
                ('years', models.CharField(blank=True, max_length=15, null=True)),
                ('carType', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
