# Generated by Django 3.2.12 on 2023-02-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0019_prospect_coveragea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='purchasePrice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
