# Generated by Django 3.2.12 on 2023-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0020_alter_prospect_purchaseprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='mailing_address',
            new_name='mailingAddress',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='mailing_address2',
            new_name='mailingAddress2',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='mailing_city',
            new_name='mailingCity',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='mailing_county',
            new_name='mailingCounty',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='mailing_state',
            new_name='mailingState',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='mailing_zipcode',
            new_name='mailingZipcode',
        ),
        migrations.AddField(
            model_name='prospect',
            name='priorAddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='priorAddress2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='priorCity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='priorCounty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='priorState',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='priorZipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
