# Generated by Django 3.2.12 on 2022-05-29 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0021_auto_20220527_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agencyAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agencyLogo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agencyWebsite',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agencyDocuments',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agencyUWFiles',
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 16, 1, 12, 710377), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 16, 1, 12, 710388), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
