# Generated by Django 3.2.12 on 2023-02-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0021_auto_20230206_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='area',
            new_name='livingArea',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='year',
            new_name='yearBuilt',
        ),
    ]
