# Generated by Django 3.2.12 on 2022-05-29 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0022_auto_20220529_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentMethod',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentRef',
            new_name='ref',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentRef2',
            new_name='ref2',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentType',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentAmount',
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 16, 24, 20, 34750), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 16, 24, 20, 34765), null=True),
        ),
    ]
