# Generated by Django 3.2.12 on 2022-05-29 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
        ('Maps', '0001_initial'),
        ('Insurance', '0023_auto_20220529_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodystyleentry',
            name='yearEntry',
        ),
        migrations.DeleteModel(
            name='CarsDB',
        ),
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='picktrimentry',
            name='bodyStyle',
        ),
        migrations.RemoveField(
            model_name='supportchat',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='supportChat',
        ),
        migrations.RemoveField(
            model_name='yearentry',
            name='model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='mileage',
            new_name='bodyStyle',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='endorsementUWFiles',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policyUWFiles',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='licensePlate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorsementFiles',
            field=models.ManyToManyField(blank=True, related_name='endorsementFiles', to='Files.File'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policyFiles',
            field=models.ManyToManyField(blank=True, related_name='policyFiles', to='Files.File'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.address'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilePicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Files.picture'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='endorsementDocuments',
            field=models.ManyToManyField(blank=True, related_name='endorsementDocuments', to='Files.File'),
        ),
        migrations.AlterField(
            model_name='homequoteelements',
            name='propertyAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.address'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 19, 3, 18, 15084), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 19, 3, 18, 15096), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policyDocuments',
            field=models.ManyToManyField(blank=True, related_name='policyDocuments', to='Files.File'),
        ),
        migrations.AlterField(
            model_name='priorinsurance',
            name='priorDocument',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Files.file'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='BodyStyleEntry',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='PersonalImage',
        ),
        migrations.DeleteModel(
            name='PickTrimEntry',
        ),
        migrations.DeleteModel(
            name='SupportChat',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
        migrations.DeleteModel(
            name='UWFile',
        ),
        migrations.DeleteModel(
            name='YearEntry',
        ),
    ]
