# Generated by Django 3.2.12 on 2022-06-18 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0024_auto_20220529_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Master'), (2, 'Agent'), (3, 'Customer')], null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 18, 14, 57, 30, 319355), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 18, 14, 57, 30, 319366), null=True),
        ),
    ]
