# Generated by Django 3.2.12 on 2022-06-18 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0025_auto_20220618_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='agency',
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 18, 19, 16, 15, 320924), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 18, 19, 16, 15, 320935), null=True),
        ),
    ]
