# Generated by Django 3.2.12 on 2022-06-25 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0030_auto_20220619_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessquoteelements',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='commercialautoquoteelements',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='healthquoteelements',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='homequoteelements',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='lifequoteelements',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='personalautoquoteelements',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='personalAutoQuoteElements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.personalautoquoteelements'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 15, 28, 29, 960757), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 15, 28, 29, 960768), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='businessType',
            field=models.CharField(blank=True, choices=[('PA', 'Personal Auto'), ('CA', 'Commercial Auto'), ('HO3', 'Homeowners'), ('HO3', 'Homeowners'), ('HO4', 'Tenant Rental'), ('HO6', 'Condo'), ('HO8', 'Custom Home'), ('HE', 'Health'), ('LI', 'Life'), ('BU', 'Business'), ('FL', 'Flood'), ('DP1', 'Fire'), ('DP2', 'Dwelling'), ('DP3', 'Rental'), ('DP4', 'Other'), ('OT', 'Other')], max_length=50, null=True),
        ),
    ]
