# Generated by Django 3.2.12 on 2022-06-25 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0032_auto_20220625_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredauto',
            name='autoquotelements',
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.namedinsured'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 24, 21, 101059), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 24, 21, 101071), null=True),
        ),
    ]
