# Generated by Django 3.2.12 on 2022-06-25 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0034_auto_20220625_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalautoquoteelements',
            name='coveredAutos',
            field=models.ManyToManyField(blank=True, null=True, to='Insurance.CoveredAuto'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 27, 13, 98279), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 27, 13, 98292), null=True),
        ),
    ]
