# Generated by Django 3.2.12 on 2022-06-25 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0035_auto_20220625_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredauto',
            name='comprehensiveDeductible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 35, 5, 455324), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 35, 5, 455337), null=True),
        ),
    ]
