# Generated by Django 3.2.12 on 2022-06-25 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0037_auto_20220625_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalautoquoteelements',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 50, 37, 870858), null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 50, 37, 870870), null=True),
        ),
    ]
