# Generated by Django 3.2.12 on 2022-06-27 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0040_auto_20220626_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredauto',
            name='car',
        ),
        migrations.RemoveField(
            model_name='personalautoquoteelements',
            name='coveredAutos',
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='autoQuote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.personalautoquoteelements'),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='bodyStyle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='licensePlate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='secondaryDriver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryDriver', to='Insurance.namedinsured'),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='trim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coveredauto',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coveredauto',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='Insurance.namedinsured'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='bindDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
