# Generated by Django 3.2.12 on 2022-12-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0042_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='roofMaterial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='burglarAlarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='centralAir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='claims',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='codob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='cofirst_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='colast_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='families',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='fireAlarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='foundation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='foundationMaterial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='foundationType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='gatedCommunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='inspections',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='loan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mailing_address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mailing_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mailing_zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='married',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mortgage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mortgagee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='occupancy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='policy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='policyType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pool',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='prior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='priorexp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='purchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='purchasePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='roofCover',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='roofDeck',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='roofType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='roofWall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='roofYear',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='wall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='waterheater',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
