# Generated by Django 3.2.12 on 2022-12-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0043_auto_20221207_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
