# Generated by Django 3.2.12 on 2023-02-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_alter_property_additionalinsureds 2'),
        ('Insurance', '0042_prospect 2'),
        ('Insurance', '0047_alter_prospect_owner'),
    ]

    operations = [
    ]
