version: '3'

services:
  backend:
    restart: always
    build: ./backsrc
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/backsrc
    working_dir: /backend
    links:
      - postgres:postgres
      - redis:redis
    environment:
      DEBUG: 'true'
    # command: /usr/local/bin/gunicorn prietoWeb.wsgi:application -w 2 -b 0.0.0.0:8081
  frontend:
    build: ./frontsrc
    ports:
      - "8080:8080"
    env_file: ./frontsrc/.env
    volumes:
      - ./frontend:/frontsrc
      - /frontend/node_modules
    working_dir: /frontend

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "8888:8888"
    volumes:
      - web-static:/www/static
    links:
      - backend:backend
      - frontend:frontend

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=donjerson
      - POSTGRES_PASSWORD=W3lcome77
      - POSTGRES_DB=smartrater
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata:
  frontend:
  backend: