version: '3'

services:
  backend:
    build: ./backsrc
    ports:
      - "8081:8081"
    volumes:
      - ./backsrc:/backend
    working_dir: /backend
    links:
      - redis:redis
    environment:
      DEBUG: 'true'
    # command: /usr/local/bin/gunicorn prietoWeb.wsgi:application -w 2 -b 0.0.0.0:8081
  frontend:
    build: ./frontsrc
    ports:
      - "8080:8080"
    env_file: ./frontsrc/.env
    volumes:
      - ./frontsrc:/frontend
      # - frontend:/frontsrc
      - frontend:/frontend/node_modules
    working_dir: /frontend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      
volumes:
  web-static:
  redisdata:
  frontend:
  backend: