#!/bin/sh

#export STATUS= "git status -uno | grep Changes"

while [ true ]; do
 
 # do what you need to here


export STATUS="\"$(cd /home/ubuntu/smartrater/backsrc && git remote show origin)\""  
SUB='not staged'

case $STATUS in
  *"$SUB"*)
    echo "$STATUS"
    ;;
esac


if [ "$STATUS" = *"$SUB"* ]; then
    echo "Up-to-Date SmartRater"
else 
    echo "q vaina er diablo e"
    cd /home/ubuntu/smartrater/backsrc
    git pull origin master
fi

    sleep 2
done