#!/bin/sh

#export STATUS= "git status -uno | grep Changes"

cd /home/ubuntu/smartrater/backsrc

while [ true ]; do

git pull --dry-run | grep -q -v 'Already up-to-date.' && changed=1

fi
    sleep 5

done