from Insurance.models import *




# Create Brands Script

# brandss= ['ACU;ACURA','ADB;ALEXANDER DENNIS','ALF;ALFA ROMEO','AUD;AUDI','BEN;BENTLEY','BMW;BMW','BUG;BUGATTI','BUI;BUICK','BCB;BYD COACH AND BUS LLC','CAD;CADILLAC','CHE;CHEVROLET','CHR;CHRYSLER','CNC;CRANE CARRIER','DOD;DODGE','FRA;FERRARA FIRE APPARATUS','FER;FERRARI','FIA;FIAT','FOR;FORD','GNS;GENESIS','GEP;GLOBAL ENVIRONMENTAL PRODUCTS','GMC;GMC','GRW;GRANDE WEST','HON;HONDA','HYU;HYUNDAI','INF;INFINITI','IRI;IRIZAR','ISU;ISUZU','JAG;JAGUAR','JEE;JEEP','KRM;KARMA AUTOMOTIVE LLC','KIA;KIA','LND;LAND ROVER','LEX;LEXUS','LIN;LINCOLN','LON;LION EBUS','LOT;LOTUS','MAS;MASERATI','MAZ;MAZDA','MCL;MCLAREN AUTOMOTIVE','MEB;MERCEDES-BENZ','MIN;MINI','MIT;MITSUBISHI','NIS;NISSAN','PLS;POLESTAR','POR;PORSCHE','TER;PROTERRA','RAM;RAM','RSB;ROSENBAUER AMERICA','SUB;SUBARU','TMP;TEMSA BUS','TES;TESLA','TIF;TIFFIN MOTORHOMES INC','TOY;TOYOTA','VLK;VOLKSWAGEN','VLV;VOLVO','XOS;XOS'
# ]

# for el in brandss:
#   vals = el.split(';')
#   brand, created = Brand.objects.get_or_create(name=vals[1],short=vals[0])
 
#   if created:
#     print("Created Brand:", brand)
#   else:
#     print("Brand already exists:", brand)