# Generated by Django 3.2.12 on 2022-09-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('short', models.CharField(blank=True, max_length=2, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('propertySearchUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('searchFunction', models.CharField(blank=True, max_length=10000, null=True)),
                ('yearBuilt', models.CharField(blank=True, max_length=100, null=True)),
                ('qualityGrade', models.CharField(blank=True, max_length=100, null=True)),
                ('squareFootage', models.CharField(blank=True, max_length=100, null=True)),
                ('land', models.CharField(blank=True, max_length=100, null=True)),
                ('landValue', models.CharField(blank=True, max_length=100, null=True)),
                ('buildingValue', models.CharField(blank=True, max_length=100, null=True)),
                ('totalBuildingArea', models.CharField(blank=True, max_length=100, null=True)),
                ('foundation', models.CharField(blank=True, max_length=100, null=True)),
                ('use', models.CharField(blank=True, max_length=100, null=True)),
                ('heatSource', models.CharField(blank=True, max_length=100, null=True)),
                ('heatMethod', models.CharField(blank=True, max_length=100, null=True)),
                ('stories', models.CharField(blank=True, max_length=100, null=True)),
                ('baths', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=100, null=True)),
                ('parcelId', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('mailingAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('patios', models.CharField(blank=True, max_length=100, null=True)),
                ('porches', models.CharField(blank=True, max_length=100, null=True)),
                ('garage', models.CharField(blank=True, max_length=100, null=True)),
                ('floorType', models.CharField(blank=True, max_length=100, null=True)),
                ('roofType', models.CharField(blank=True, max_length=100, null=True)),
                ('roofShape', models.CharField(blank=True, max_length=100, null=True)),
                ('roofCover', models.CharField(blank=True, max_length=100, null=True)),
                ('wallHeight', models.CharField(blank=True, max_length=100, null=True)),
                ('extWall', models.CharField(blank=True, max_length=100, null=True)),
                ('intWall', models.CharField(blank=True, max_length=100, null=True)),
                ('pool', models.CharField(blank=True, max_length=100, null=True)),
                ('purchasePrice', models.IntegerField(blank=True, null=True)),
                ('purchaseDate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.county')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('short', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.country')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.state'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.county')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('cityObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.city')),
                ('countyObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county', to='Maps.county')),
                ('stateObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.state')),
                ('zipcodeObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.zipcode')),
            ],
        ),
    ]
