# Generated by Django 3.2.12 on 2022-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='purchasePrice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
