# Generated by Django 3.2.12 on 2022-06-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0002_auto_20220619_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='short',
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maps.state'),
        ),
    ]
